# Generated by Django 5.1.6 on 2025-02-13 00:00

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_address_line1_profile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='cover_default.png', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
