# Generated by Django 5.1.6 on 2025-02-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Incoming Money', 'Incoming Money'), ('Payments', 'Payments'), ('Withdrawals', 'Withdrawals'), ('Airtime Purchase', 'Airtime Purchase'), ('Bank Transfer', 'Bank Transfer'), ('Unknown', 'Unknown'), ('Data Bundle Purchase', 'Data Bundle Purchase'), ('Bank Deposit', 'Bank Deposit'), ('Business Payment', 'Business Payment'), ('Failed Transaction', 'Failed Transaction'), ('Fund Transfer', 'Fund Transfer')], default='Unknown', max_length=50)),
                ('sender', models.CharField(max_length=100)),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient', models.CharField(max_length=100)),
                ('recipient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(default='RWF', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('external_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('date_sent', models.DateTimeField()),
                ('readable_date', models.CharField(max_length=100)),
                ('service_center', models.CharField(max_length=50)),
                ('account_balance', models.IntegerField(default=0)),
                ('transaction_fee', models.IntegerField()),
                ('raw_message', models.TextField()),
            ],
        ),
    ]
